kind: List

items:
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: anomaly-detection # this requires that there is an image stream with this name? 
    labels:
      build: anomaly-detection
      app:  anomaly-detection
    
  spec:
    lookupPolicy:
      local: true


- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  
  metadata:
    labels:
      app: anomaly-detection
      build: anomaly-detection
    name: anomaly-detection
  spec:
    triggers:
      - generic:
          secret: abef1035f7e8528b
        type: Generic
      - github:
          secret: 104e14d978977712
        type: GitHub
      - imageChange:
          lastTriggeredImageID: >-
            registry.access.redhat.com/rhscl/python-36-rhel7@sha256:faa41271420f7e198e887f74cdcdad89474dc13acde54a227bb5fbe40fe1ead7
        type: ImageChange
      - type: ConfigChange

    source:
      git:
        ref: master
        uri: 'git@gitlab.cee.redhat.com:mcliffor/AO_AD_POC.git'
      sourceSecret:
        name: repo-at-gitlab
      type: Git
    
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'python:3.6'
          namespace: openshift
      type: Source
    
    output:
      to:
        kind: ImageStreamTag
        name: 'anomaly-detection:latest'
    
    
    
- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  
  metadata:
    labels:
      app: anomaly-detection
    name: anomaly-detection
  spec:
    replicas: 1
    selector:
      deploymentconfig: anomaly-detection
    template:
      metadata:
        labels:
          app: anomaly-detection
          deploymentconfig: anomaly-detection
      spec:
        containers:
          - env:
            - name: LADT_ELASTICSEARCH_ENDPOINT
              value: "http://elasticsearch.perf.lab.eng.bos.redhat.com:9280"
            - name: LADT_MODEL
              value: map.sav
            - name: LADT_INDEX
              value: logstash-
            - name: LADT_TIME_SPAN
              value: "900"
            - name: LADT_MAX_ENTRIES
              value: "25000"
            - name: LADT_ITERS
              value: "25000"
            - name: LADT_SERVICE
              value: journal
            - name: LADI_ELASTICSEARCH_ENDPOINT
              value: http://elasticsearch.perf.lab.eng.bos.redhat.com:9280
            - name: LADI_MODEL
              value: map.sav
            - name: LADI_INDEX
              value: logstash-
            - name: LADI_OUTDEX
              value: mcliffor_test_ingest
            - name: LADI_TIME_SPAN
              value: "60"
            - name: LADI_MAX_ENTRIES
              value: "250"
            - name: LADI_SERVICE
              value: journal
            - name: LADI_THRESHOLD
              value: "0.99"
            - name: LADI_MAX_ANOMALIES
              value: "5"
            image: anomaly-detection:latest
            imagePullPolicy: Always
            name: anomaly-detection-deploy
            resources:
              limits:
                memory: 2Gi
                cpu: 2
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
      - type: ConfigChange
      - type: "imagechange"
        imageChange:
          from:
            kind: "ImageStreamTag"
            name: "anomaly-detection:latest"

